version: '3.8'

services:
  geoipupdate:
    container_name: geoip_update
    image: maxmindinc/geoipupdate:latest
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIPUPDATE_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City GeoLite2-Country GeoLite2-ASN
      - GEOIPUPDATE_FREQUENCY=${GEOIPUPDATE_FREQUENCY}
    volumes:
      - ./data:/usr/share/GeoIP
    restart: always

  api:
    container_name: geoip_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - geoipupdate
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./data:/usr/share/GeoIP
    restart: always

networks:
  default:
    driver: bridge
